### Building a machine learning model to predict player's position and his rating

In [8]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [9]:
import zipfile
with zipfile.ZipFile("archive.zip") as z:
    with z.open("male_players.csv") as f:
        data = pd.read_csv(f)

data.head()

C:\Users\pranj\AppData\Local\Temp\ipykernel_21436\1152988356.py:4: DtypeWarning: Columns (108) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(f)


player_id                             player_url  fifa_version  \
0     231747    /player/231747/kylian-mbappe/240002          24.0   
1     239085   /player/239085/erling-haaland/240002          24.0   
2     192985  /player/192985/kevin-de-bruyne/240002          24.0   
3     158023     /player/158023/lionel-messi/240002          24.0   
4     165153    /player/165153/karim-benzema/240002          24.0   

   fifa_update update_as_of    short_name                       long_name  \
0          2.0   2023-09-22     K. Mbappé            Kylian Mbappé Lottin   
1          2.0   2023-09-22    E. Haaland            Erling Braut Haaland   
2          2.0   2023-09-22  K. De Bruyne                 Kevin De Bruyne   
3          2.0   2023-09-22      L. Messi  Lionel Andrés Messi Cuccittini   
4          2.0   2023-09-22    K. Benzema                   Karim Benzema   

  player_positions  overall  potential    value_eur  wage_eur  age  \
0           ST, LW       91         94  181500000.0  230000.0   24   
1               ST       91         94  185000000.0  340000.0   22   
2          CM, CAM       91         91  103000000.0  350000.0   32   
3          CF, CAM       90         90   41000000.0   23000.0   36   
4           CF, ST       90         90   51000000.0   95000.0   35   

          dob  height_cm  weight_kg  club_team_id            club_name  \
0  1998-12-20        182         75          73.0  Paris Saint Germain   
1  2000-07-21        195         94          10.0      Manchester City   
2  1991-06-28        181         75          10.0      Manchester City   
3  1987-06-24        169         67      112893.0          Inter Miami   
4  1987-12-19        185         81         607.0           Al Ittihad   

   league_id          league_name  league_level club_position  \
0       16.0              Ligue 1           1.0            LW   
1       13.0       Premier League           1.0            ST   
2       13.0       Premier League           1.0           SUB   
3       39.0  Major League Soccer           1.0            RF   
4      350.0           Pro League           1.0            RS   

   club_jersey_number club_loaned_from club_joined_date  \
0                 7.0              NaN       2018-07-01   
1                 9.0              NaN       2022-07-01   
2                17.0              NaN       2015-08-30   
3                10.0              NaN       2023-07-16   
4                 9.0              NaN       2023-07-01   

   club_contract_valid_until_year  nationality_id nationality_name  \
0                          2024.0              18           France   
1                          2027.0              36           Norway   
2                          2025.0               7          Belgium   
3                          2025.0              52        Argentina   
4                          2026.0              18           France   

   nation_team_id nation_position  nation_jersey_number preferred_foot  \
0          1335.0              LW                  10.0          Right   
1          1352.0              ST                   9.0           Left   
2          1325.0             CAM                   7.0          Right   
3          1369.0              RW                  10.0           Left   
4             NaN             NaN                   NaN          Right   

   weak_foot  skill_moves  international_reputation      work_rate  \
0          4            5                         5       High/Low   
1          3            3                         5    High/Medium   
2          5            4                         5    High/Medium   
3          4            4                         5        Low/Low   
4          4            4                         5  Medium/Medium   

          body_type real_face  release_clause_eur  \
0            Unique       Yes         349400000.0   
1            Unique       Yes         356100000.0   
2            Unique       Yes         190600000.0   
3            U

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180021 entries, 0 to 180020
Columns: 109 entries, player_id to gk
dtypes: float64(20), int64(43), object(46)
memory usage: 149.7+ MB


In [11]:
data = data.drop(['player_id','player_url','fifa_version','fifa_update','update_as_of','short_name','long_name','dob','club_team_id',
                  'league_id','club_loaned_from','club_joined_date','club_contract_valid_until_year','nationality_id','nation_team_id',
                 'player_tags','player_traits','value_eur','wage_eur','height_cm','weight_kg','club_name','league_name','club_jersey_number','nationality_name',
           'nation_jersey_number','preferred_foot','body_type','real_face','release_clause_eur','potential','club_position','nation_position'], axis = 1)

### Data preprocessing

In [12]:
cols_to_modify = ['ls','st','rs','lw','lf','cf','rf','rw','lam','cam','ram','lm','lcm','cm','rcm','rm','lwb','ldm','cdm','rdm','rwb','lb','lcb','cb','rcb','rb','gk']

In [13]:
def add_values(value):
    if '+' in str(value):
        parts = str(value).split('+')
        return int(parts[0]) + int(parts[1])
    elif '-' in str(value):
        parts = str(value).split('-')
        return int(parts[0]) - int(parts[1])
    else:
        return int(value)
#data[[col+'_org', col+'_grow']] = data[col].str.split('+', expand = True)

In [14]:
for col in cols_to_modify:
    data[col] = data[col].apply(add_values)

In [15]:
def replace_nan(data):
    for column in data.columns:
        if pd.api.types.is_numeric_dtype(data[column]):
            data[column].fillna(0, inplace=True)
        else:
            data[column].fillna('Not Applicable', inplace=True)

In [16]:
replace_nan(data)

In [17]:
data[['work_rate_attack','work_rate_defence']] = data['work_rate'].str.split('/', expand=True)

In [18]:
data.drop('work_rate', axis = 1, inplace = True)

In [19]:
def player_position_trim(value):
    trim_pos = str(value).split(',')
    return trim_pos[0]

In [20]:
data['player_positions'] = data['player_positions'].apply(player_position_trim)

In [21]:
conditions = [
    (data['player_positions'] == 'CF') | (data['player_positions'] == 'LW') | (data['player_positions'] == 'RW') | (data['player_positions'] == 'ST'),
    (data['player_positions'] == 'RM') | (data['player_positions'] == 'LM') | (data['player_positions'] == 'CM') | (data['player_positions'] == 'CAM') | (data['player_positions'] == 'CDM'),
    (data['player_positions'] == 'CB') | (data['player_positions'] == 'RB') | (data['player_positions'] == 'LB') | (data['player_positions'] == 'RWB') | (data['player_positions'] == 'LWB'),
    (data['player_positions'] == 'GK')]

values = ['Forward', 'Midfielder', 'Defender', 'Goalkeeper']

data['position_4'] = np.select(conditions, values, default='Other')

In [22]:
data.head()

player_positions  overall  age  league_level  weak_foot  skill_moves  \
0               ST       91   24           1.0          4            5   
1               ST       91   22           1.0          3            3   
2               CM       91   32           1.0          5            4   
3               CF       90   36           1.0          4            4   
4               CF       90   35           1.0          4            4   

   international_reputation  pace  shooting  passing  dribbling  defending  \
0                         5  97.0      90.0     80.0       92.0       36.0   
1                         5  89.0      93.0     66.0       80.0       45.0   
2                         5  72.0      88.0     94.0       87.0       65.0   
3                         5  80.0      87.0     90.0       94.0       33.0   
4                         5  79.0      88.0     83.0       87.0       39.0   

   physic  attacking_crossing  attacking_finishing  \
0    78.0                  78                   94   
1    88.0                  47                   96   
2    78.0                  95                   85   
3    64.0                  83                   89   
4    78.0                  75                   91   

   attacking_heading_accuracy  attacking_short_passing  attacking_volleys  \
0                          73                       86                 84   
1                          83                       77                 90   
2                          55                       94                 83   
3                          60                       91                 86   
4                          90                       89                 88   

   skill_dribbling  skill_curve  skill_fk_accuracy  skill_long_passing  \
0               93           80                 69                  71   
1               79           77                 62                  53   
2               86           92                 83                  94   
3               96           93                 93                  90   
4               87           82                 73                  76   

   skill_ball_control  movement_acceleration  movement_sprint_speed  \
0                  92                     97                     97   
1                  82                     82                     94   
2                  92                     72                     72   
3                  93                     87                     74   
4                  91                     78                     79   

   movement_agility  movement_reactions  movement_balance  power_shot_power  \
0                93                  93                82                90   
1                76                  94                72                94   
2                74                  92                78                92   
3                91                  88                95                83   
4                77                  92                72                87   

   power_jumping  power_stamina  power_strength  power_long_shots  \
0             88             88              77                83   
1             93             76              93                86   
2             72             88              74                92   
3             71             70              68                90   
4             85             82              82                81   

   mentality_aggression  mentality_interceptions  mentality_positioning  \
0                    64                       38                     93   
1                    87                       43                     96   
2                    75                       66                     88   
3                    44                       40                     91   
4                    63                       39                     92   

   mentality_vision  mentality_penalties  mentality_composure  \
0                83   

In [23]:
data_num = data.drop(['player_positions','overall','league_level','weak_foot','skill_moves','international_reputation','work_rate_attack',
                     'work_rate_defence','position_4'], axis = 1)
data_ord = data[['league_level','weak_foot','skill_moves','international_reputation',]]

data_cat = data[['work_rate_attack','work_rate_defence']]

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in data_cat:
    data_cat[col] = pd.DataFrame(le.fit_transform(data_cat[col]), columns = [col])

C:\Users\pranj\AppData\Local\Temp\ipykernel_21436\1900511266.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cat[col] = pd.DataFrame(le.fit_transform(data_cat[col]), columns = [col])
C:\Users\pranj\AppData\Local\Temp\ipykernel_21436\1900511266.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cat[col] = pd.DataFrame(le.fit_transform(data_cat[col]), columns = [col])


In [25]:
X = pd.concat([data_num, data_ord, data_cat], axis = 1)

In [26]:
Y = data['position_4']

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_std = pd.DataFrame(sc.fit_transform(X), columns = X.columns)

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_std,Y,test_size=0.3,random_state=42)

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,multilabel_confusion_matrix
rfc = RandomForestClassifier(n_estimators=50)
rfc.fit(X_train,Y_train)
Y_pred_4 = rfc.predict(X_test)

In [30]:
accuracy_score(Y_test,Y_pred_4)

0.9207695298757569

In [31]:
precision_score(Y_test,Y_pred_4, average = None)

array([0.95040252, 0.89237392, 1.        , 0.88472679])

In [32]:
recall_score(Y_test,Y_pred_4, average = None)

array([0.9588232 , 0.84018529, 1.        , 0.90471409])

In [33]:
multilabel_confusion_matrix(Y_test, Y_pred_4)

array([[[35519,   881],
        [  725, 16882]],

       [[42595,  1050],
        [ 1656,  8706]],

       [[47888,     0],
        [    0,  6119]],

       [[31740,  2348],
        [ 1898, 18021]]], dtype=int64)

In [34]:
Y = data['player_positions']

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_std,Y,test_size=0.3,random_state=78)

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,multilabel_confusion_matrix
rfc = RandomForestClassifier(n_estimators=50)
rfc.fit(X_train,Y_train)
Y_pred = rfc.predict(X_test)

In [37]:
accuracy_score(Y_test,Y_pred)

0.767159812616883

In [38]:
precision_score(Y_test,Y_pred, average = None)

array([0.63857466, 0.91179913, 0.7497657 , 0.75581395, 0.69972596,
       0.99983496, 0.64938212, 0.49140893, 0.52262443, 0.48051948,
       0.6761242 , 0.50319189, 0.58634538, 0.5       , 0.86696544])

In [39]:
recall_score(Y_test,Y_pred, average = None)

array([0.66470415, 0.93334785, 0.72644722, 0.17857143, 0.85219326,
       1.        , 0.70656472, 0.48310811, 0.21076642, 0.11044776,
       0.63820111, 0.459849  , 0.23453815, 0.10062893, 0.95591678])

In [40]:
multilabel_confusion_matrix(Y_test, Y_pred)

array([[[49332,  1278],
        [ 1139,  2258]],

       [[43996,   829],
        [  612,  8570]],

       [[48534,  1068],
        [ 1205,  3200]],

       [[53622,    21],
        [  299,    65]],

       [[45414,  2301],
        [  930,  5362]],

       [[47948,     1],
        [    0,  6058]],

       [[48767,  1447],
        [ 1113,  2680]],

       [[49567,  1480],
        [ 1530,  1430]],

       [[52700,   211],
        [  865,   231]],

       [[53632,    40],
        [  298,    37]],

       [[48839,  1210],
        [ 1432,  2526]],

       [[49770,  1323],
        [ 1574,  1340]],

       [[52556,   206],
        [  953,   292]],

       [[53657,    32],
        [  286,    32]],

       [[45189,  1128],
        [  339,  7351]]], dtype=int64)

In [43]:
Y = data['overall']
Y.head()

0    91
1    91
2    91
3    90
4    90
Name: overall, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_std,Y,test_size=0.3,random_state=42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
regressor = RandomForestRegressor(n_estimators=50, random_state=56)
regressor.fit(X_train, Y_train)
predictions = regressor.predict(X_test)
mse = mean_squared_error(Y_test, predictions)
print(f'Mean Squared Error: {mse}')
r2 = r2_score(Y_test, predictions)
print(f'R-squared: {r2}')

Mean Squared Error: 0.49023780621030605
R-squared: 0.9900884320681439
